DROP DATABASE IF EXISTS ACEF;

CREATE DATABASE ACEF;
GO
USE ACEF;
GO
CREATE TABLE [dbo].[RAISON](
	[ID] INT IDENTITY(1,1) NOT NULL,
	[NomRaison] NVARCHAR(50) NOT NULL,
	[IsActive] BIT NOT NULL default 'TRUE',
	CONSTRAINT [PK_RAISON] PRIMARY KEY CLUSTERED ([ID])
);